repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: react-persisted-global-state

  # A short description of the repository that will show up on GitHub
  description: A React library providing a hook for global, cross-tab, and Local Storage persisted state 📦 .

  # A URL with more information about the repository
  homepage: https://www.npmjs.com/package/react-persisted-global-state

  # A comma-separated list of topics to set on the repository
  topics: react, hooks, state, global, persist, local-storage, github-actions, npm

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true

labels:
  - name: Feature Request
    color: a9f913

  - name: Improvement
    color: f9d0c4

  - name: Bug
    color: b60205

  - name: dependencies

  - name: yarn

  - name: GitHub Actions
